name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  setup:
    name: 'Setup'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.41.2-jammy
    steps:
      - uses: actions/checkout@v3
        
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
  api:
   name: 'Countries REST API Tests'
   needs: [setup]
   runs-on: ubuntu-latest
   container:
     image: oven/bun
   steps:     
      - uses: actions/checkout@v3
      - name: Restore node_modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
   
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci

      - name: Execute API tests
        run: bun test
        env:
          HOME: /root
  ui:
   name: 'MarketWatch UI Tests'
   needs: [setup]
   runs-on: ubuntu-latest
   container:
     image: mcr.microsoft.com/playwright:v1.41.2-jammy
   steps:     
      - uses: actions/checkout@v3
      - name: Restore node_modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci

      - name: Generate BDD Tests
        run: npx bddgen

      - name: Execute UI tests
        run: npx playwright test --project chromium firefox webkit
        env:
          HOME: /root